version: '3.4'

x-restart-policy: &restart_policy
  restart: unless-stopped

x-defaults: &defaults
  <<: *restart_policy
  image: tryzealot/zealot:nightly
  depends_on:
    - redis
    - postgres
  env_file: .env
  environment:
    ZEALOT_REDIS_HOST: redis
    ZEALOT_POSTGRES_HOST: postgres
  volumes:
    - zealot-data:/app/public
    - ./log:/app/log
  healthcheck:
    test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/health || exit 1"]
  logging:
    driver: json-file
    options:
      max-size: 1g
      max-file: 10
      max-buffer-size: 4m
      mode: non-blocking

services:
  redis:
    <<: *restart_policy
    container_name: zealot-redis
    image: redis:5-alpine
    command: redis-server
    volumes:
      - zealot-redis:/var/lib/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  postgres:
    <<: *restart_policy
    container_name: zealot-postgres
    image: postgres:12-alpine
    volumes:
      - zealot-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ze@l0t
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  zealot:
    <<: *defaults
    container_name: zealot-zealot
