  web:
    <<: *restart_policy
    container_name: zealot-web
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./rootfs/etc/Caddyfile:/etc/Caddyfile
      - ./rootfs/etc/certs:/etc/certs
      - zealot-data:/app/public
    env_file: .env
